language: java
jdk:
  - openjdk17
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app : "book-demo-store"
  on:
    branch: main

before_install:
  - chmod +x ./gradlew

script:
  - ./gradlew build
