language: java
jdk:
  - openjdk17

before_install:
  - chmod +x gradlew
  - bash -c "source ~/.rvm/scripts/rvm"  # Ensure RVM is loaded properly using bash -c
  - rvm install 3.0.0 --default  # Install Ruby 3.0.0 and set it as default
  - rvm use 3.0.0 --default      # Confirm Ruby 3.0.0 is in use
  - ruby -v                      # Verify the Ruby version being used
  - gem install bundler
  - bundle install
  - chmod +x deploy.sh  # Make the deploy.sh script executable

script:
  - ./gradlew assemble

deploy:
  script: ./deploy.sh  # Use the custom deploy script
