language: java
jdk:
  - openjdk17

before_install:
  - rvm install 3.0.0 --default              # Install Ruby 3.0.0 and set it as default
  - rvm use 3.0.0 --default                  # Ensure Ruby 3.0.0 is the default version
  - ruby -v                                  # Check that Ruby 3.0.0 is in use
  - which ruby                               # Confirm the path to Ruby
  - gem install bundler                      # Install bundler
  - gem install faraday-net_http -v 3.0.2    # Install faraday-net_http version 3.0.2
  - gem install dpl -v 1.10.16               # Install dpl manually
  - chmod +x ./gradlew

script:
  - ./gradlew build

deploy:
  provider: script
  script:
    - rvm use 3.0.0 --default               # Re-ensure Ruby 3.0.0 during deploy
    - ruby -v                               # Confirm Ruby 3.0.0 during deploy
    - gem install faraday-net_http -v 3.0.2 # Re-install required gem in deploy phase
    - dpl --provider=heroku --app="book-demo-store" --api-key=$HEROKU_TOKEN
  on:
    branch: main
