language: java
jdk:
  - openjdk17

before_install:
  - chmod +x ./gradlew
  - curl https://cli-assets.heroku.com/install.sh | sh

script:
  - ./gradlew build

deploy:
  skip_cleanup: true
  provider: script
  script:
    - heroku auth:token
    - heroku git:remote -a book-demo-store
    - git push heroku main
  on:
    branch: main
