language: java
jdk:
  - openjdk17

before_install:
  - sudo apt-get update
  - sudo apt-get install -y ruby-build chruby
  - ruby-install ruby 3.0.0            # Install Ruby 3.0.0 with chruby
  - chruby ruby-3.0.0                  # Use Ruby 3.0.0
  - ruby -v                            # Verify Ruby version
  - gem install bundler                # Install Bundler
  - gem install faraday-net_http -v 3.0.2  # Install faraday-net_http version 3.0.2
  - chmod +x ./gradlew

script:
  - ./gradlew build

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-demo-store"
  on:
    branch: main
