language: java
jdk:
  - openjdk17

before_install:
  - echo "Starting RVM setup"
  - bash -c "source $HOME/.rvm/scripts/rvm || source /usr/local/rvm/scripts/rvm"  # Ensure RVM is sourced correctly
  - rvm install 3.0.0 --default
  - rvm use 3.0.0 --default
  - ruby -v
  - echo "RVM setup complete, starting Gem installation"
  - gem install bundler
  - gem install faraday-net_http -v 3.0.2
  - gem install dpl -v 1.10.16
  - echo "Gem installation complete, making gradlew executable"
  - chmod +x ./gradlew

script:
  - ./gradlew build  # Run your build script

before_deploy:
  - git config --global user.email "mohamedcherrou2000@gmail.com"
  - git config --global user.name "Cherrou Mohamed"
  - git remote add heroku https://git.heroku.com/book-demo-store.git  # Ensure Heroku remote is added
  - git add -A
  - git commit -m "Auto-commit from Travis CI" || true  # Prevent failure if no changes to commit

deploy:
  provider: script
  script:
    - bash -c "source $HOME/.rvm/scripts/rvm || source /usr/local/rvm/scripts/rvm"
    - rvm use 3.0.0 --default
    - git push heroku `git subtree split --prefix . main`:refs/heads/main --force  # Push to Heroku
  on:
    branch: main  # Deploy only when changes are pushed to the main branch
