language: java
jdk:
  - openjdk17

before_install:
  - chmod +x gradlew
  - gem install bundler
  - bundle install

script:
  - ./gradlew assemble

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-demo-store"
  on:
    branch: main
