language: java
jdk:
  - openjdk17

before_install:
  - chmod +x gradlew
  - rvm install 3.0.0 --default  # Install Ruby 3.0.0 and set it as the default
  - rvm use 3.0.0 --default      # Reaffirm using Ruby 3.0.0 as the default
  - rvm --default use 3.0.0      # Another way to enforce Ruby 3.0.0
  - ruby -v                      # Verify Ruby version
  - gem install bundler
  - bundle install

script:
  - ./gradlew assemble

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-demo-store"
  on:
    branch: main
