language: java
jdk:
  - openjdk17

before_install:
  - bash --login                                # Ensure a login shell is used
  - rvm install 3.0.0 --default                 # Install Ruby 3.0.0 and set it as default
  - rvm use 3.0.0 --default                     # Ensure Ruby 3.0.0 is the default version
  - ruby -v                                     # Check that Ruby 3.0.0 is in use
  - which ruby                                  # Confirm the path to Ruby
  - gem install bundler                         # Install bundler
  - gem install faraday-net_http -v 3.0.2       # Install faraday-net_http version 3.0.2
  - gem install dpl -v 1.10.16                  # Install dpl manually if needed
  - chmod +x ./gradlew                          # Make gradlew executable if needed

script:
  - ./gradlew build                             # Run your build script

before_deploy:
  - git config --global user.email "mohamedcherrou2000@gmail.com"
  - git config --global user.name "Cherrou Mohamed"
  - git add -A
  - git commit -m "Auto-commit from Travis CI"  # Auto-commit any changes before deployment

deploy:
  provider: script
  script:
    - rvm use 3.0.0 --default                   # Re-ensure Ruby 3.0.0 during deploy
    - ruby -v                                   # Confirm Ruby 3.0.0 during deploy
    - gem install faraday-net_http -v 3.0.2     # Re-install required gem in deploy phase
    - dpl --provider=heroku --app="book-demo-store" --api-key=$HEROKU_TOKEN
  on:
    branch: main                                # Deploy only when changes are pushed to the main branch
