language: java
jdk:
  - openjdk17

before_install:
  - rvm install 3.0.0 --default  # Install and set Ruby 3.0.0 as default
  - rvm use 3.0.0 --default      # Ensure Ruby 3.0.0 is used globally
  - rvm list                     # List installed Ruby versions for confirmation
  - ruby -v                      # Verify Ruby version
  - which ruby                   # Verify the path of Ruby
  - gem install bundler          # Install Bundler to manage Ruby gems
  - gem install dpl -v 1.10.16   # Manually install dpl version 1.10.16
  - chmod +x ./gradlew

script:
  - ./gradlew build
before_deploy:
  - git config --global user.email "mohamedcherrou2000@gmail.com"  # Set your email
  - git config --global user.name "Cherrou Mohamed"         # Set your name
  - git add -A                                        # Add all changes
  - git commit -m "Automated commit before deploy"    # Commit changes

deploy:
  provider: script
  script: dpl --provider=heroku --app="book-demo-store" --api-key=$HEROKU_TOKEN
  on:
    branch: main
