language: java
jdk:
  - openjdk17

before_install:
  - source ~/.rvm/scripts/rvm  # Source RVM scripts
  - rvm install 3.0.0 --default
  - rvm use 3.0.0 --default
  - ruby -v
  - gem install bundler
  - bundle install


script:
  - ./gradlew assemble

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-demo-store"
  on:
    branch: main
  ruby: 3.0.0   # Specify Ruby version directly in the deploy step
