language: java
jdk:
  - openjdk17

before_install:
  - chmod +x gradlew
  - rvm install 3.0.0  # Install Ruby 3.0.0
  - rvm use 3.0.0 --default      # Set Ruby 3.0.0 as the default Ruby version
  - ruby -v             # Verify the Ruby version
  - gem install bundler
  - bundle install

script:
  - ./gradlew assemble

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-demo-store"
  on:
    branch: main
