language: java
jdk:
  - openjdk17

before_install:
  - sudo apt-get update
  - sudo apt-get install -y ruby-build chruby
  - ruby-install ruby 3.0.0            # Install Ruby 3.0.0 with chruby
  - chruby ruby-3.0.0                  # Use Ruby 3.0.0
  - ruby -v                            # Verify Ruby version
  - gem install bundler                # Install Bundler
  - gem install faraday-net_http -v 3.0.2  # Install faraday-net_http version 3.0.2
  - gem install dpl -v 1.10.16             # Manually install dpl version 1.10.16
  - chmod +x ./gradlew

script:
  - ./gradlew build

deploy:
  provider: script
  script: |
    chruby ruby-3.0.0                # Re-ensure Ruby 3.0.0 during deploy
    ruby -v                          # Confirm Ruby 3.0.0 during deploy
    gem install faraday-net_http -v 3.0.2  # Re-install required gem in deploy phase
    dpl --provider=heroku --app="book-demo-store" --api-key=$HEROKU_TOKEN
  on:
    branch: main
